- name: Install packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - python3-pip
    - ipython

- name: Upgrade pip
  pip: name=pip3 state=latest

- name: Install requirements
  pip:
    requirements: /blog-it/requirements.txt
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: python3.5
