# ------- #
# PROJECT #
# ------- #


project_name: "blog_it"
user: "{{ django }}"
application_dir: "/blog-it"
backend_path: "{{ application_dir }}/project"
temp_dir: "/tmp"
virtualenv_dir: "/home/{{ user }}/.virtualenvs/{{ project_name }}"
python_requirements: "{{ application_dir }}/requirements.txt"
python_version: "python3.4"

# ---------- #
# POSTGRESQL #
# ---------- #

postgresql_version: 9.3
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_ctype: 'en_US.UTF-8'
postgresql_admin_user: "postgres"

postgresql_databases:
  - name: "{{ project_name }}"
    owner: "{{ user }}"
